### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by ankitsridhar16** [ankitsridhar16/heft#3]

**Comment by ankitsridhar16** [comment]
sure @tanryberdi

**Comment by gis-gmd** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayercommunity.online/XY2wna)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others
  - Ethereum Mainnet
  - Binance Mainnet

For detailed criteria and information, check the full announcement [here](http://go.altlayercommunity.online/XY2wna).

[Claim Airdrop Altlayer](http://go.altlayercommunity.online/XY2wna) opens from January 25 to February 03, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
dev-starlight, @AidenLee0408, @KONY128, @watertim, @arsalanvaloojerdi, @zhenghao111, @alex-core-0x, @3bodymo, @weazyexe, @aaronmorannn, @pawiromitchel, @SMC2004, @Tok1t4N1k0, @johanpaolorodriguez, @a1-0s, @sereverol, @yosephbernandus, @Kinfung21, @huzaifamk, @tomzhang
